title: WMIC Process Creation
id: 4
status: experimental
description: Detects wmic spawning processes
author: OGT WatchTower
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: 'wmic.exe'
        CommandLine|contains: 'process call create'
    condition: selection
level: medium
