title: MSHTA Network Execution
id: 3
status: experimental
description: Detects mshta executing remote content
author: OGT WatchTower
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: 'mshta.exe'
        CommandLine|contains:
            - 'http://'
            - 'https://'
            - 'javascript:'
            - 'vbscript:'
    condition: selection
level: high
