title: PowerShell Download
id: 5
status: experimental
description: Detects PowerShell downloading content
author: OGT WatchTower
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: 'powershell.exe'
        CommandLine|contains:
            - 'downloadstring'
            - 'downloadfile'
            - 'invoke-webrequest'
            - 'iwr'
            - 'wget'
    condition: selection
level: high
