title: PowerShell Encoded Command
id: 2
status: experimental
description: Detects PowerShell running with encoded commands
author: OGT WatchTower
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        Image|endswith: 'powershell.exe'
        CommandLine|contains:
            - '-encodedcommand'
            - ' -e '
            - ' -en '
    condition: selection
level: medium
